// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *archive → potpotpot*
 */
export interface ArchiveDocumentDataPotpotpotItem {
  /**
   * name field in *archive → potpotpot*
   *
   * - **Field Type**: Text
   * - **Placeholder**: name
   * - **API ID Path**: archive.potpotpot[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * price field in *archive → potpotpot*
   *
   * - **Field Type**: Number
   * - **Placeholder**: price
   * - **API ID Path**: archive.potpotpot[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * image field in *archive → potpotpot*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.potpotpot[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for archive documents
 */
interface ArchiveDocumentData {
  /**
   * potpotpot field in *archive*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.potpotpot[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  potpotpot: prismic.GroupField<Simplify<ArchiveDocumentDataPotpotpotItem>>;
}

/**
 * archive document from Prismic
 *
 * - **API ID**: `archive`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArchiveDocumentData>,
    "archive",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for pot documents
 */
interface PotDocumentData {
  /**
   * name field in *pot*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This Pot has no Name
   * - **API ID Path**: pot.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * price field in *pot*
   *
   * - **Field Type**: Number
   * - **Placeholder**: This Pot has no Price
   * - **API ID Path**: pot.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * image field in *pot*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pot.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * pot document from Prismic
 *
 * - **API ID**: `pot`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PotDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PotDocumentData>, "pot", Lang>;

export type AllDocumentTypes = ArchiveDocument | HomepageDocument | PotDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArchiveDocument,
      ArchiveDocumentData,
      ArchiveDocumentDataPotpotpotItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PotDocument,
      PotDocumentData,
      AllDocumentTypes,
    };
  }
}
