import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { PrismicPreview } from '@prismicio/next'
import { createClient, repositoryName } from '@/prismicio'
import './globals.css'
import { Footer } from '@/components/Footer'
import { asLink } from '@prismicio/client'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = createClient()

  const page = await client.getSingle('footer')
  const { facebook, instagram, website } = page.data
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <PrismicPreview repositoryName={repositoryName} />
        <Footer
          website={asLink(website) as string}
          instagram={asLink(instagram) as string}
          facebook={asLink(facebook) as string}
        />
      </body>
    </html>
  )
}
