import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  single,
}: {
  children: React.ReactNode
  single: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        {single}
        <PrismicPreview repositoryName={repositoryName} />
        <div id="modal-root"></div>
      </body>
    </html>
  )
}
